name: Run Backward Compat. Tests

# When to run tests.
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  dependabot-metadata:
    uses: ./.github/workflows/_dependabot-metadata.yml
    secrets: inherit

  tests:
    needs: [dependabot-metadata]

    # Always allow non-Dependabot PRs and pushes.
    # For Dependabot PRs, only run when the update is for composer (skip github-actions updates).
    if: |
      always() &&
      (
        github.actor != 'dependabot[bot]' ||
        needs.dependabot-metadata.outputs.package-ecosystem == 'composer'
      )

    uses: ./.github/workflows/_run-tests.yml
    secrets: inherit
    with:
      # WordPress 6.2.8 with apiVersion 2 blocks. We test specific block tests
      # that historically depended on apiVersion 2 behaviour.
      wp-versions: '["6.2.8"]'
      php-versions: '["8.1"]'
      test-groups: |
        [
          "EndToEnd/broadcasts/blocks-shortcodes/PageBlockBroadcastsCest",
          "EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest",
          "EndToEnd/forms/blocks-shortcodes/PageBlockFormCest",
          "EndToEnd/forms/blocks-shortcodes/PageBlockFormTriggerCest",
          "EndToEnd/products/PageBlockFormatterProductLinkCest",
          "EndToEnd/products/PageBlockProductCest"
        ]
      block-editor-v3-enabled: 'false'
      db-sql-dump-file: 'tests/Support/Data/dump-6.2.8.sql'
      install-plugins-urls: 'https://downloads.wordpress.org/plugin/block-visibility.3.3.0.zip'
